apiVersion: v1
kind: Service
metadata:
  annotations: 
    botkube.io/disable: true
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
